### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by SowinskiBraeden** [unjs/redirect-ssl#42]
I am coming back to my website project, and have noticed the `exclude: ['localhost']` doesnt work. While working locally it still redirects to https and prevents me from connecting to the local website.

**Comment by nelhop** [comment]
Any update on this? I am facing the same error.

**Comment by matthewfee** [comment]
I am facing the same error on this as well.

**Comment by vicky1246** [comment]
Yes , It is not working at all.

**Comment by tpwatson** [comment]
> Yes , It is not working at all.

Was having this issue as well, but when I visited my localhost from an incognito browser it worked!

It's possible that the browser has cached a redirect response from a previous request and automatically redirecting to the HTTPS version of the site. So could be the browser doing that before the application gets a chance to work properly.

And it kinda makes sense, if the a website has moved to a new place, the browser wont even try to get a response from the old place, it will just remember the new place and head straight there to improve user experience.

**Comment by SowinskiBraeden** [comment]
That seems like a very reasonable answer @tpwatson I am going to close my original issue now.
